# Explore NSDUH Data

In [1]:
import pandas as pd
import numpy as np
import pathlib
import statsmodels.formula.api as smf

## Set working directories

In [2]:
repo_f = pathlib.Path.cwd().parent.parent
code_f = repo_f.joinpath('code')
input_f = repo_f.joinpath('input')
output_f = repo_f.joinpath('output')

## Load in Data

In [3]:
infile = input_f.joinpath('NSDUH/nonmj_test_2019_1pct.csv')
df_test = pd.read_csv(infile)
df_test.head()

,Unnamed: 0,agegrp,marstat,male,edu,race,employ,income,famincome,poverty,actual
0,0,15,3,1,5,7,4,1,1,1,0
1,1,8,4,1,9,7,4,1,1,1,0
2,2,11,1,2,6,7,2,1,3,1,0
3,3,15,4,2,8,7,4,2,3,2,0
4,4,15,1,2,11,1,2,2,4,2,0

In [4]:
infile = input_f.joinpath('NSDUH/nonmj_train_2019_1pct.csv')
df_train = pd.read_csv(infile)
df_train.head()

,Unnamed: 0,agegrp,marstat,male,edu,race,employ,income,famincome,poverty,actual
0,0,7,4,1,9,7,1,1,7,3,0
1,1,13,1,2,11,7,4,1,7,3,0
2,2,3,0,1,4,7,0,1,3,2,0
3,3,16,1,1,11,1,4,3,7,3,0
4,4,2,0,2,2,6,0,1,7,3,0

In [5]:
infile = input_f.joinpath('NSDUH/nonmj_validate_2019_1pct.csv')
df_validate = pd.read_csv(infile)
df_validate.head()

,Unnamed: 0,agegrp,marstat,male,edu,race,employ,income,famincome,poverty,actual
0,0,16,1,1,11,5,1,7,7,3,0
1,1,16,1,1,8,7,1,6,7,3,0
2,2,14,1,1,11,5,1,7,7,3,0
3,3,15,4,2,8,1,1,1,4,2,1
4,4,15,1,1,8,1,1,3,5,3,0

In [6]:
infile = input_f.joinpath('NSDUH/nonmj_resampled_2019_1pct.csv')
df_resampled = pd.read_csv(infile)
df_resampled.head()

,Unnamed: 0,agegrp,marstat,male,edu,race,employ,income,famincome,poverty,actual
0,0,7,4,1,9,7,1,1,7,3,0
1,1,13,1,2,11,7,4,1,7,3,0
2,2,3,0,1,4,7,0,1,3,2,0
3,3,16,1,1,11,1,4,3,7,3,0
4,4,2,0,2,2,6,0,1,7,3,0

In [7]:
print("Number of obs: ", df_test.shape[0])
df_test['actual'].value_counts(normalize=True)

Number of obs:  272795

0    0.910728
1    0.089272
Name: actual, dtype: float64

In [8]:
print("Number of obs: ", df_train.shape[0])

df_train['actual'].value_counts(normalize=True)

Number of obs:  371082

0    0.911044
1    0.088956
Name: actual, dtype: float64

In [9]:
print("Number of obs: ", df_validate.shape[0])

df_validate['actual'].value_counts(normalize=True)

Number of obs:  182772

0    0.911431
1    0.088569
Name: actual, dtype: float64

In [10]:
print("Number of obs: ", df_resampled.shape[0])

df_resampled['actual'].value_counts(normalize=True)

Number of obs:  676144

0    0.5
1    0.5
Name: actual, dtype: float64

### Concat train and validate

Autogluon will create validation datasets for us so we can just combine validate and train into large traning set

In [11]:
df_train = pd.concat([df_train, df_validate], ignore_index=True)

## Distribution of drug use by race

In [12]:
f_x = 'actual ~ C(race)'

train_race = smf.ols(formula=f_x, data=df_train).fit(cov_type='HC3')
train_race.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 actual   R-squared:                       0.001
Model:                            OLS   Adj. R-squared:                  0.001
Method:                 Least Squares   F-statistic:                     136.8
Date:                Mon, 09 Jan 2023   Prob (F-statistic):          6.65e-174
Time:                        15:39:32   Log-Likelihood:                -89366.
No. Observations:              553854   AIC:                         1.787e+05
Df Residuals:                  553847   BIC:                         1.788e+05
Df Model:                           6
Covariance Type:                  HC3
================================================================================
                   coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept        0.0907      0.000    194.923      0.000       0.090       0.092
C(race)[T.2]    -0.0158      0.001    -12.775      0.000      -0.018      -0.013
C(race)[T.3]     0.0200      0.005      3.889      0.000       0.010       0.030
C(race)[T.4]    -0.0026      0.007     -0.381      0.704      -0.016       0.011
C(race)[T.5]    -0.0392      0.002    -23.896      0.000      -0.042      -0.036
C(race)[T.6]     0.0219      0.003      7.398      0.000       0.016       0.028
C(race)[T.7]     0.0027      0.001      2.463      0.014       0.001       0.005
==============================================================================
Omnibus:                   312202.337   Durbin-Watson:                   2.001
Prob(Omnibus):                  0.000   Jarque-Bera (JB):          1696169.023
Skew:                           2.886   Prob(JB):                         0.00
Kurtosis:                       9.340   Cond. No.                         18.2
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)
"""

In [13]:
f_x = 'actual ~ C(race)'

test_race = smf.ols(formula=f_x, data=df_test).fit(cov_type='HC3')
test_race.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 actual   R-squared:                       0.001
Model:                            OLS   Adj. R-squared:                  0.001
Method:                 Least Squares   F-statistic:                     79.15
Date:                Mon, 09 Jan 2023   Prob (F-statistic):           2.59e-99
Time:                        15:39:33   Log-Likelihood:                -44608.
No. Observations:              272795   AIC:                         8.923e+04
Df Residuals:                  272788   BIC:                         8.930e+04
Df Model:                           6
Covariance Type:                  HC3
================================================================================
                   coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept        0.0916      0.001    137.609      0.000       0.090       0.093
C(race)[T.2]    -0.0189      0.002    -10.744      0.000      -0.022      -0.015
C(race)[T.3]     0.0112      0.007      1.570      0.116      -0.003       0.025
C(race)[T.4]     0.0144      0.010      1.405      0.160      -0.006       0.035
C(race)[T.5]    -0.0415      0.002    -18.095      0.000      -0.046      -0.037
C(race)[T.6]     0.0216      0.004      5.099      0.000       0.013       0.030
C(race)[T.7]     0.0021      0.002      1.312      0.189      -0.001       0.005
==============================================================================
Omnibus:                   153145.132   Durbin-Watson:                   1.999
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           824456.377
Skew:                           2.875   Prob(JB):                         0.00
Kurtosis:                       9.282   Cond. No.                         17.7
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)
"""

## Create a function that does what we just did

In [14]:
def get_data(dep_var):
    infile = input_f.joinpath('NSDUH/' + dep_var + '_test_2019_1pct.csv')
    df_test = pd.read_csv(infile)
    infile = input_f.joinpath('NSDUH/' + dep_var + '_train_2019_1pct.csv')
    df_train = pd.read_csv(infile)
    infile = input_f.joinpath('NSDUH/' + dep_var + '_validate_2019_1pct.csv')
    df_validate = pd.read_csv(infile)
    df_train = pd.concat([df_train, df_validate], ignore_index=True)

    infile = input_f.joinpath('NSDUH/' + dep_var + '_resampled_2019_1pct.csv')
    df_resampled = pd.read_csv(infile)

    return df_train, df_test, df_resampled

In [15]:
def mean_diff(df, category):
    f_x = 'actual ~ C({})'.format(category)

    results = smf.ols(formula=f_x, data=df).fit(cov_type='HC3')
    print(results.summary())

In [16]:
df_train, df_test, df_resampled = get_data('sales')

In [17]:
mean_diff(df_train, 'race')

                            OLS Regression Results
==============================================================================
Dep. Variable:                 actual   R-squared:                       0.001
Model:                            OLS   Adj. R-squared:                  0.001
Method:                 Least Squares   F-statistic:                     132.1
Date:                Mon, 09 Jan 2023   Prob (F-statistic):          8.01e-168
Time:                        15:39:37   Log-Likelihood:             3.8975e+05
No. Observations:              553854   AIC:                        -7.795e+05
Df Residuals:                  553847   BIC:                        -7.794e+05
Df Model:                           6
Covariance Type:                  HC3
================================================================================
                   coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------
Intercept        0.0137      0.000     72.849      0.000       0.013       0.014
C(race)[T.2]    -0.0004      0.001     -0.818      0.413      -0.001       0.001
C(race)[T.3]     0.0064      0.002      2.797      0.005       0.002       0.011
C(race)[T.4]     0.0035      0.003      1.128      0.259      -0.003       0.010
C(race)[T.5]    -0.0102      0.000    -21.798      0.000      -0.011      -0.009
C(race)[T.6]     0.0141      0.002      9.194      0.000       0.011       0.017
C(race)[T.7]     0.0057      0.001     11.131      0.000       0.005       0.007
==============================================================================
Omnibus:                   744843.890   Durbin-Watson:                   2.001
Prob(Omnibus):                  0.000   Jarque-Bera (JB):         99406951.164
Skew:                           8.096   Prob(JB):                         0.00
Kurtosis:                      66.603   Cond. No.                         18.2
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)

## Find an interesting pattern on your own!!